spring:
  datasource:
    url: jdbc:mysql:///day19?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3000
#mybatis配置规则
#mybatis:
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml